-- ACSA events + registrations (Postgres)

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  attendees INTEGER NOT NULL DEFAULT 0,
  max_attendees INTEGER NOT NULL DEFAULT 0,
  category TEXT NOT NULL DEFAULT '',
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  image TEXT NOT NULL DEFAULT '',
  registration_limit INTEGER,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  club_year TEXT NOT NULL DEFAULT '2026-27',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS registrations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  usn TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL,
  phone TEXT NOT NULL DEFAULT '',
  branch_name TEXT NOT NULL DEFAULT '',
  academic_year TEXT NOT NULL DEFAULT '',
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS events_club_year_idx ON events (club_year);
CREATE INDEX IF NOT EXISTS registrations_event_id_idx ON registrations (event_id);
CREATE INDEX IF NOT EXISTS registrations_email_idx ON registrations (lower(email));
